services:
  playwright-monitor:
    build: .
    container_name: playwright-monitor-container
    working_dir: /usr/src/app
    command: ["node", "dist/monitor.js"]
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials as read-only
      - ./config.json:/usr/src/app/config.json:ro  # Mount the external config file as read-only
    stdin_open: true
    tty: true