services:
  playwright-monitor:
    build:
      context: .
      dockerfile: Containerfile
    container_name: playwright-monitor-container
    # restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && npm run build && npm start"